### ISSUE TITLE
[Runtime Crash] Symbol splitting not working correctly in subroutines

### ISSUE THREAD

**Issue by fleupold** [JacobEberhardt/ZoKrates#95] opened 2018-07-31 13:39 UTC
Assume the following sample code I want to create a witness for (I stripped off meaningful things for simplicity):

```
def sub():
  foo = if 1 < 2 then 1 else 2 fi
  return 1

def main():
   return sub()
```

It compiles fine. However computing a witness leads to the following error:

```
thread 'main' panicked at 'no entry found for key', libcore/option.rs:917:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

In particular I believe that [this line](https://github.com/JacobEberhardt/ZoKrates/blob/develop/src/flat_absy.rs#L290) causes the crash. Printing `var_name` and `inputs`, I can see that:

```
Inputs: {"sub_i0o1_1_sym_0": 1, "sub_i0o1_1_sym_1": 2, "sub_i0o1_1_sym_2": 21888242871839275222246405745257275088548364400416034343698204186575808495615, "~one": 1}
Variable name: "sym_2"
```

`sym_2` does not exist and we therefore crash. I assume that either `sub_i0o1_1_sym_2` in inputs should be `sym_2` (without the subroutine prefix) or sym_2 should be prefixed accordingly.

**Comment by Schaeff** [comment] 2018-07-31 17:24
Thanks for reporting this

**Comment by Schaeff** [comment] 2018-07-31 21:08
@fleupold I tried your example and couldn't reproduce the issue (witness generation worked fine), which commit were you using?

**Comment by Schaeff** [comment] 2018-08-01 10:02
Thanks for checking, @Kyroy what's our current strategy for the docker releases? From the report above, it appears the dockerhub version could be out of sync with master?

**Comment by Kyroy** [comment] 2018-08-01 11:29
@Schaeff I manually uploaded all old versions from kyroy/zokrates to zokrates/zokrates (0.1, 0.2). So 0.2 ist also latest.
The policy is: When you push to master, it is uploaded.

The current master branch does not yet include the new release to zokrates/zokrates.

**Comment by fleupold** [comment] 2018-08-01 13:37
Not sure if this should be a separate issue, but I ran into a similar crash on master today, when trying to compute a witness for code that can be simplified to:

```
def sub(a):
  a = a + 3
  return a

def main():
   a = 4
   return sub(a)
```

Again it compiled, but when computing a witness it crashed with: 
```
thread 'main' panicked at 'Variable "sub_i1o1_1_a" is undeclared in inputs: {"a": 4, "sub_i1o1_1_param_0": 4, "~one": 1}', src/flat_absy.rs:302:25
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I assume it has something to do with reassigning a function parameter while also using it in the assignment. Seems like a pretty edgy case, but something that should be allowed?

Workaround was to introduce a separate variable instead of reassigning `a`.

**Comment by Schaeff** [comment] 2018-08-01 14:40
Thanks @fleupold I'm able to reproduce this one, could you open another issue with this? I'll close this one as the original bug was fixed but not yet in master

**Closed by Schaeff** 2018-08-01 14:40 UTC
Labels: bug
